# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b50e7ebd7138c379251bee300344ff8a51233a2d490766eea4334fc8df3238d0eadb3df06fb2bc159b95e948b6c037693ebf36a6c98b1d784c730e09709e0bf6

test:
  secret_key_base: 5c95764b559568d9cffbc3fbb1cde5e6dd90a4cd85ebec7c9841fc25d4f7b3fcaf86925b36b8dd93f5c601a0079bb12d07ac5395345bf96ecd5e81a7e3ee9e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
